SHEETY_ENDPOINT = "#Sheety Endpoint"
TEQUILA_ENDPOINT = "#Tequila Endpoint"
TEQUILA_URL = "#Tequila URL"
ACCOUNT_SID = "#Twilio Account ID"
AUTH_TOKEN = "#Twilio Auth Token"
TWILIO_PHONE = "#Twilio Phone Number"
PERSONAL_PHONE = "#Receiver Message Phone Number"
